version: '3.4'
services:
  mysql:
    image: percona:8.0
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: yggdrasil
      MYSQL_PASSWORD: yggdrasil
      MYSQL_DATABASE: communication_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  api:
    image: p2_11_api:1.0
    network_mode: "host"
    depends_on:
      - mysql
    command: ["uvicorn", "main:app", "--reload", "--port", "9000" ]
  agent:
    image: p2_11_agent:1.0
    network_mode: "host"
    depends_on:
      - api
    command: ["java", "-jar", "./build/libs/Agent-all.skill" ]

